### ISSUE TITLE
How to enable and access SikuliX OCR functions 

### ISSUE THREAD

**Issue by jips11in** [sterodium/selenium-grid-extensions#50]
I was trying to find text() method on ScreenRegion Object but its not available. Can you please confirm if I can use OCR functionality of SikuliX and how?

**Comment by jips11in** [comment]
If you can give me the pointer , I can help to add sikuli OCR functionality if its not added yet? Any input would be very helpful.

**Comment by echoAlexey** [comment]
Hi @jips11in, as you can see we are using old Sikuli library - 

```
<dependency>
       <groupId>org.sikuli</groupId>
       <artifactId>sikuli-api</artifactId>
       <version>1.2.0</version>
</dependency>
```
It would be a good idea to migrate to SikuliX :+1: 

We are not actively maintaining this project, but if you are ready to contribute we can provide support from our side.

**Comment by echoAlexey** [comment]
SkX Not supported.
