### ISSUE TITLE
Unable to upload resource and unable to parse response data from grid.

### ISSUE THREAD

**Issue by sguess** [sterodium/selenium-grid-extensions#57]
Hi 
In `RemoteInvoker `class `invoke(String widgetId, Method method, Object[] arguments)`  function, the `restClient.invoke(widgetId, methodInvocationDto);` return a html, but it should be return a json. Then, the `GSON.fromJson(response, MethodInvocationResultDto.class);` occurred exception. 

I try to run sample "GoogleSearchTest.java", when the process executed `sikuliExtensionClient.uploadResourceBundle(GOOGLE_IMAGES_BUNDLE);`, 
It looked the selenium grid response a html content as below 
![1](https://user-images.githubusercontent.com/13902130/30474374-12dde836-9a36-11e7-9b4d-be167d357e8e.jpg)

Thanks
Daniel

**Comment by echoAlexey** [comment]
try version 1.0
