### ISSUE TITLE
new grid extension release required

### ISSUE THREAD

**Issue by shankarkc** [sterodium/selenium-grid-extensions#61]
Due to selenium grid changes , selenium grid extension stopped working and I submited a pull request to fix the same. But new release is not available yet in maven repository. @echoAlexey I really depreciate if you please release a new version with my changes. Many of my tests need these changes. I cannot move to new version because of Sikuli is broken there.
Thanks
Shankar KC

**Comment by shankarkc** [comment]
@echoAlexey I still dont see 0.7 version available on maven repository. Can you pls reopen this?

**Comment by echoAlexey** [comment]
@shankarkc look for 1.0
  http://repo1.maven.org/maven2/io/sterodium/selenium-grid-extensions/1.0/

**Comment by shankarkc** [comment]
My bad. Thanks @echoAlexey  I will use it.
