### ISSUE TITLE
Is there any good reason why maven repo is still on 0.6 version

### ISSUE THREAD

**Issue by misko-frame** [sterodium/selenium-grid-extensions#62]
Is there any good reason why maven repo is still on 0.6 version?
The project I am working on depends on this project...
Is there a chance in near future to publish latest sterodium stuff on https://mvnrepository.com/artifact/io.sterodium

P.S. I can always choose 'dark force path', fork whole project, and continue from my local repo... but ... you know... 
Do you still support this library via maven or not?

**Comment by echoAlexey** [comment]
1.0 should be in mvn central in few hours ;) Depends on how fast they are. 

I do not supporti this library, but welcome PR.
