### ISSUE TITLE
File download failing intermittently because of Null pointer exception coming from SeleniumSessions.refreshTimeout() method

### ISSUE THREAD

**Issue by sjethvani** [sterodium/selenium-grid-extensions#63]
I am using this selenium-grid-extensions for downloading files and comparing them with expected ones . Most of the times it works smooth and gives me proper result . However sometimes I do see that testcase fails while downloading file with following exception trace.  Any one having any idea ?

`Exception io.sterodium.extensions.client.download.FileDownloadException
Message: Response returned code 500, with message: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 500 Server Error</title> </head> <body><h2>HTTP ERROR 500</h2> <p>Problem accessing /grid/admin/HubRequestsProxyingServlet/session/9dfb5c6adb9efe05d530cfa5292e2cb8/FileDownloadServlet/C%3A%2FSelenium_Download_Stuff%2FCrosstab_SavedExpressionMeasure_AggregationSum_CustomSummaryAllc0214122238875.xlsx. Reason: <pre> Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NullPointerException at io.sterodium.extensions.hub.proxy.session.SeleniumSessions.refreshTimeout(SeleniumSessions.java:35) at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.createExtensionClient(HubRequestsProxyingServlet.java:82) at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.forwardRequest(HubRequestsProxyingServlet.java:62) at io.sterodium.extensions.hub.proxy.HubRequestsProxyingServlet.doGet(HubRequestsProxyingServlet.java:40) at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841) at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535) at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595) at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473) at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564) at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155) at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.seleniumhq.jetty9.server.Server.handle(Server.java:561) at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334) at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251) at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104) at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247) at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140) at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679) at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597) at java.lang.Thread.run(Thread.java:748) </pre> <hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.7.v20170914</a><hr/> </body> </html>`

**Comment by sjethvani** [comment]
This [function](https://github.com/sterodium/selenium-grid-extensions/blob/5d86c292b24e493a6fdb5b486f026253c5ca2901/hub-extensions/extension-proxy/src/main/java/io/sterodium/extensions/hub/proxy/session/SeleniumSessions.java#L33) needs to be updated 

Updated one 
`    public void refreshTimeout(String sessionId) {
        for (TestSession activeSession : registry.getActiveSessions()) {
            if ((activeSession != null) && (sessionId != null) && (activeSession.getExternalKey() != null)) {
                if (sessionId.equals(activeSession.getExternalKey().getKey())) {
                    refreshTimeout(activeSession);
                }
            }
        }
    }`

PS : I have added null verification on potential probable objects . 

Let me know how you guys think . I can submit PR if you guys want 

@echoAlexey  , @buzdin  @volkovs  @shankarkc @braindonor

**Comment by echoAlexey** [comment]
submit PR.
