### ISSUE TITLE
Download file fails if spaces in names are exist

### ISSUE THREAD

**Issue by myznikov** [sterodium/selenium-grid-extensions#68]
Hello All,
We found out files with spaces in names cannot be downloaded or deleted due to one-directional UrlEncode on clients without of UrlDecode on servlets. So symbols ' ' are being translated to '+' and file cannpt be found.
I have two solutions:
1. Add UrlDecode to _FileDownloadServlet_ and _FileDeleteServlet_. It works while we don't try to download file with symbol '+' in name. It's always translated back to ' ' during decoding, so file name becames incorrect again.
1.  Use _java.util.Base64.getUrlEncoder_. It works always correctly but URLs are going to be not human-readable. 

I have both solutions working locally, so can make Pull request for any of them.

**Comment by echoAlexey** [comment]
Hi, @myznikov , you can make PR and I will merge it :) 
I don't use this project atm and don't have time to improve it.

**Comment by myznikov** [comment]
I was not sure what of two alternative soulutions should be pushed. 
If you do not want to make a decision too, I prefer to use base64 encoding then.
